name: CI
on:
  push: { branches: [ main, master ] }
  pull_request: { branches: [ main, master ] }
  workflow_dispatch:
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10', '3.11' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install ruff black mypy pytest pytest-cov
      - name: Lint (ruff)
        run: ruff check .
      # - name: Format check (black)
      #   run: black --check .
      - name: Type check (mypy)
        run: mypy . || true
      - name: Tests
        run: PYTHONPATH=. pytest -q --maxfail=1 --disable-warnings --cov --cov-report=xml
      - name: Upload to Codecov
        if: ${{ env.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ env.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: false
