name: Snyk Security

on:
  pull_request:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Snyk disabled (missing token)
        if: ${{ secrets.SNYK_TOKEN == '' }}
        run: echo "Snyk skipped: set SNYK_TOKEN secret to enable."

      - uses: actions/checkout@v4
        if: ${{ secrets.SNYK_TOKEN != '' }}

      - uses: actions/setup-python@v5
        if: ${{ secrets.SNYK_TOKEN != '' }}
        with:
          python-version: '3.11'

      - name: Install deps
        if: ${{ secrets.SNYK_TOKEN != '' }}
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt || true

      - name: Snyk Code
        if: ${{ secrets.SNYK_TOKEN != '' }}
        uses: snyk/actions/python@master
        with:
          args: --severity-threshold=high --sarif-file-output=snyk-code.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload SARIF
        if: ${{ secrets.SNYK_TOKEN != '' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif

  container:
    runs-on: ubuntu-latest
    steps:
      - name: Snyk disabled (missing token)
        if: ${{ secrets.SNYK_TOKEN == '' }}
        run: echo "Snyk skipped: set SNYK_TOKEN secret to enable."

      - uses: actions/checkout@v4
        if: ${{ secrets.SNYK_TOKEN != '' }}

      - name: Build image (no push)
        if: ${{ secrets.SNYK_TOKEN != '' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Containerfile
          push: false
          load: true
          tags: openanalyst-studio:snyk

      - name: Snyk Container
        if: ${{ secrets.SNYK_TOKEN != '' }}
        uses: snyk/actions/docker@master
        with:
          image: app:snyk
          args: --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
